DROP TABLE IF EXISTS AD_SUPPLIER_PERFORMANCE_DATA;

CREATE TABLE AD_SUPPLIER_PERFORMANCE_DATA
(
    ID               INT AUTO_INCREMENT PRIMARY KEY,
    BATCH_JOB_ID     UUID         NOT NULL,
    AD_SDK           VARCHAR(15)  NOT NULL,
    COUNTRY          VARCHAR(20)  NOT NULL,
    AD_TYPE          VARCHAR(250) NOT NULL,
    PERFORMANCE_RATE INT(2)       NOT NULL
);

CREATE INDEX "AD_SUPPLIER_PERFORMANCE_DATA_BATCH_JOB_ID" ON AD_SUPPLIER_PERFORMANCE_DATA ("BATCH_JOB_ID");
CREATE INDEX "AD_SUPPLIER_PERFORMANCE_ID_DESC" ON AD_SUPPLIER_PERFORMANCE_DATA ("ID" DESC);


DROP TABLE IF EXISTS CLUSTER_RECORD;

CREATE TABLE CLUSTER_RECORD
(
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    APPLICATION_URL VARCHAR(200) NOT NULL,
    STATUS          VARCHAR(20) NOT NULL
);

CREATE INDEX "CLUSTER_RECORD_APPLICATION_URL" ON CLUSTER_RECORD ("APPLICATION_URL");