DROP TABLE IF EXISTS billionaires;

CREATE TABLE billionaires
(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(250) NOT NULL,
    last_name  VARCHAR(250) NOT NULL,
    career     VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS AD_SUPPLIER_PERFORMANCE_DATA;

CREATE TABLE AD_SUPPLIER_PERFORMANCE_DATA
(
    ID               INT AUTO_INCREMENT PRIMARY KEY,
    BATCH_JOB_ID     UUID  NOT NULL,
    AD_SDK           VARCHAR(15)  NOT NULL,
    COUNTRY          VARCHAR(20)  NOT NULL,
    AD_TYPE          VARCHAR(250) NOT NULL,
    PERFORMANCE_RATE INT(2)    NOT NULL,
    TIMESTAMP        TIMESTAMP    NOT NULL
);